---
# SPDX-FileCopyrightText: 2025 The SayWare development team
#
# SPDX-License-Identifier: CC0-1.0
name: Build the malware
on:
  push:
jobs:
  malware:
    name: Build the malware
    runs-on: ubuntu-latest
    if: forge.ref == format('refs/heads/{0}', vars.BUILDING_BRANCH)
    env:
      CARGO_TERM_COLOR: always
      CARGO_TARGET_X86_64_PC_WINDOWS_MSVC_LINKER: lld
      RUSTFLAGS: -Lnative=./.xwin-cache/splat/crt/lib/x86_64 -Lnative=./.xwin-cache/splat/sdk/lib/um/x86_64
        -Lnative=./.xwin-cache/splat/sdk/lib/ucrt/x86_64
    steps:
      - name: Checkout code
        uses: https://data.forgejo.org/actions/checkout@v4
      - name: Check configuration changes
        uses: https://github.com/dorny/paths-filter@v3
        id: changes
        with:
          base: ${{ forge.ref }}
          filters: |
            configuration:
              - '${{ vars.CONFIGURATION_FILE_PATH }}'
      - name: Install LLD
        if: steps.changes.outputs.configuration == 'true'
        run: >
          apt-get update && apt-get install -y lld
      - name: Install Rust toolchain
        if: steps.changes.outputs.configuration == 'true' '
        uses: https://github.com/dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-pc-windows-msvc
          components: rust-src
      - name: Add Rust caching
        if: steps.changes.outputs.configuration == 'true'
        uses: https://github.com/Swatinem/rust-cache@v2
      - name: Install xwin
        if: steps.changes.outputs.configuration == 'true'
        run: cargo install --locked xwin
      - name: Add xwin caching
        if: steps.changes.outputs.configuration == 'true'
        id: cache-xwin
        uses: https://data.forgejo.org/actions/cache@v4
        with:
          path: .xwin-cache/
          key: xwin-${{ runner.os }}
      - name: Install Microsoft CRT/SDK headers and libraries
        if: steps.changes.outputs.configuration == 'true' && steps.cache-xwin.outputs.cache-hit
          != 'true'
        run: xwin --accept-license splat
      - name: Build Rust code
        if: steps.changes.outputs.configuration == 'true'
        run: cargo build --target x86_64-pc-windows-msvc --bin sayware --profile small-size
          -Z build-std=std,panic_abort -Z build-std-features="optimize_for_size" -Z
          build-std-features=panic_immediate_abort
